import Link from "next/link";

const futureFeatures = ["Permit management", "Occupancy forecasting", "Mobile attendant mode"];

export default function HomePage() {
  return (
    <main className="min-h-screen bg-slate-950 text-slate-100"><div className="mx-auto max-w-6xl px-6 py-6 sm:px-10">
      <nav className="flex items-center justify-between border-b border-slate-800 pb-6"><Link href="/" className="flex items-center gap-3 font-semibold tracking-tight"><span className="grid h-9 w-9 place-items-center rounded-lg bg-cyan-400 font-black text-slate-950">P</span>ParkFlow</Link><div className="flex items-center gap-3 text-sm"><Link href="/login" className="rounded-lg px-4 py-2 text-slate-300 hover:bg-slate-900">Log in</Link><Link href="/register" className="rounded-lg bg-cyan-400 px-4 py-2 font-semibold text-slate-950 hover:bg-cyan-300">Create account</Link></div></nav>
      <section className="grid gap-14 py-20 lg:grid-cols-[1.1fr_0.9fr] lg:items-center lg:py-28"><div><p className="mb-5 text-sm font-semibold uppercase tracking-[0.24em] text-cyan-300">Garage operations, simplified</p><h1 className="max-w-3xl text-5xl font-semibold leading-[1.05] tracking-tight sm:text-7xl">Know every space. Move every vehicle.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-400">ParkFlow gives garage teams one reliable place to manage capacity, assign compatible spots, and keep every parking session moving.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/dashboard" className="rounded-lg bg-cyan-400 px-5 py-3 font-semibold text-slate-950 hover:bg-cyan-300">Open dashboard</Link><Link href="/register" className="rounded-lg border border-slate-700 px-5 py-3 font-semibold text-slate-200 hover:border-slate-500">Start with ParkFlow</Link></div></div>
        <div className="rounded-2xl border border-slate-800 bg-slate-900 p-6 shadow-2xl"><div className="mb-8 flex items-center justify-between border-b border-slate-800 pb-5"><div><p className="text-sm text-slate-400">Garage overview</p><p className="mt-1 text-2xl font-semibold">Today at a glance</p></div><span className="rounded-full bg-emerald-400/10 px-3 py-1 text-xs font-semibold text-emerald-300">Live data</span></div><div className="grid grid-cols-2 gap-3">{["Available spaces", "Active vehicles", "EV spaces", "Open sessions"].map((label) => <div key={label} className="rounded-xl border border-slate-800 bg-slate-950 p-4"><p className="text-sm text-slate-500">{label}</p><p className="mt-3 text-3xl font-semibold text-slate-200">—</p></div>)}</div><p className="mt-5 text-sm leading-6 text-slate-500">Open the dashboard to connect to live garage data.</p></div>
      </section>
      <section className="border-t border-slate-800 py-16"><div className="grid gap-10 md:grid-cols-3"><div><p className="text-sm font-semibold uppercase tracking-wider text-cyan-300">What it is</p><p className="mt-3 leading-7 text-slate-400">A practical management system for multi-level parking facilities.</p></div><div><p className="text-sm font-semibold uppercase tracking-wider text-cyan-300">Who it helps</p><p className="mt-3 leading-7 text-slate-400">Operators, attendants, and facility teams who need a clear view of capacity.</p></div><div><p className="text-sm font-semibold uppercase tracking-wider text-cyan-300">Why it helps</p><p className="mt-3 leading-7 text-slate-400">Fewer manual lookups, faster hand-offs, and reliable spot availability.</p></div></div></section>
      <section className="border-t border-slate-800 py-16"><p className="text-sm font-semibold uppercase tracking-wider text-cyan-300">Core features</p><div className="mt-7 grid gap-4 sm:grid-cols-3">{["Compatible automatic assignment", "Live availability and EV counts", "Searchable session history"].map((feature) => <div key={feature} className="border-l-2 border-cyan-400 pl-4 text-lg text-slate-200">{feature}</div>)}</div><p className="mt-14 text-sm font-semibold uppercase tracking-wider text-slate-500">Future features</p><div className="mt-5 grid gap-3 sm:grid-cols-3">{futureFeatures.map((feature) => <div key={feature} className="rounded-xl border border-slate-800 p-4 text-slate-400">{feature}</div>)}</div></section>
      <footer className="flex flex-col gap-4 border-t border-slate-800 py-8 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between"><span>ParkFlow</span><span>Built for focused garage operations.</span></footer>
    </div></main>
  );
}
